# @name login
POST https://cognito-idp.eu-west-1.amazonaws.com/
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{
    "AuthFlow": "USER_PASSWORD_AUTH",
    "ClientId": "{{WEB_COGNITO_USER_POOL_CLIENT_ID}}",
    "AuthParameters": {
      "USERNAME": "{{test-user-name}}",
      "PASSWORD": "{{test-user-password}}"
    }
}