# @import ./login.http

# @forceRef login
@accessToken = {{login.AuthenticationResult.AccessToken}}

# @name tweet
POST {{API_URL}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-REQUEST-TYPE: GraphQL

mutation Tweet {
  tweet(text: "Hello from httpyac!") {
    id
  }
}